### ISSUE TITLE
[AVM Module Issue]: Deploy App Gateway

### ISSUE THREAD

**Issue by gsuttie** [Azure/bicep-registry-modules#3322]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/network/application-gateway

### (Optional) Module Version

latest

### Description

Hi folks

I am trying to deploy App Gateway and running into this issue - not super helpful any ideas what the cause might be?

I just need Bicep to deploy a default app gateway and then I'll add the other settnigs later.

Cannot parse the request. (Code: InvalidRequestFormat)
System.ArgumentNullException: Value cannot be null.
Parameter name: groupName (Code: InvalidRequestFormat)
System.ArgumentNullException: Value cannot be null.
Parameter name: groupName (Code: InvalidRequestFormat)
System.ArgumentNullException: Value cannot be null.
Parameter name: groupName (Code: InvalidRequestFormat)
System.ArgumentNullException: Value cannot be null.
Parameter name: groupName (Code: InvalidRequestFormat)
System.ArgumentNullException: Value cannot be null.
Parameter name: groupName (Code: InvalidRequestFormat)
System.ArgumentNullException: Value cannot be null.
Parameter name: groupName (Code: InvalidRequestFormat)
System.ArgumentNullException: Value cannot be null.
Parameter name: groupName (Code: InvalidRequestFormat)
System.ArgumentNullException: Value cannot be null.
Parameter name: groupName (Code: InvalidRequestFormat)

### (Optional) Correlation Id

dee4d0d9-d5e2-46fc-b446-b2e685fcc762

**Comment by gsuttie** [comment]
I figured this out but my question is I need to deploy a default App Gateway in a Landing Zone project and then update it in a different project - is it possible to add say a backendpool to an existing App Gateway?

**Comment by ilhaan** [comment]
@gsuttie I haven't added new backendpools to an existing AppGateway directly before, but I have created new ingresses in an AKS cluster tied to an AppGateway. Creating new ingresses just adds new backendpools to the AppGateway, so I don't see why you couldn't do this directly.

**Comment by ilhaan** [comment]
@gsuttie Gonna close this issue for now. Feel free to re-open if you still have issues.

**Comment by gsuttie** [comment]
That's fine thanks

**Comment by aavdberg** [comment]
I am also running into this problem. 

@gsuttie how you fixed it and what is the problem, because can't find the parameter 'groupName' anywhere in the code.

@jtracey93 do you know what this might be?

**Comment by gsuttie** [comment]
> I am also running into this problem. Deploying a new Application Gateway so nu updating existing one.
> 
> [@gsuttie](https://github.com/gsuttie) how you fixed it and what is the problem, because can't find the parameter 'groupName' anywhere in the code.
> 
> [@jtracey93](https://github.com/jtracey93) do you know what this might be?

Hi aavdberg

That error test is super unhelpful and cannot recall how i fixed it tbh. But here is my code that does work


module createApplicationGateway '../modules/network/application-gateway/main.bicep' = {
  scope: resourceGroup(rg_network)
  name: applicationGatewayName
  params: {
    name: applicationGatewayName
    location: location
    sku: 'WAF_v2'
    tags: tags
    diagnosticSettings: [
      {
        workspaceResourceId: logAnalytics.outputs.resourceId
      }
    ]
    firewallPolicyResourceId: createApplicationGatewayWafPolicy.outputs.resourceId
    gatewayIPConfigurations: [
      {
        name: 'appGatewayIpConfig'
        properties: {
          subnet: {
            id: '/subscriptions/${subscriptionId}/resourceGroups/${rg_network}/providers/Microsoft.Network/virtualNetworks/${hubVnet.outputs.name}/subnets/AppGwSubnet'
          }
        }
      }
    ]
    frontendIPConfigurations: [
      {
        name: 'appGwPublicFrontendIp'
        properties: {
          privateIPAllocationMethod: 'Dynamic'
          publicIPAddress: {
            id: createPublicIPAddressForAppGateway.outputs.resourceId
          }
        }
      }
    ]
    frontendPorts: [
      {
        name: 'port_80'
        properties: {
          port: 80
        }
      }
    ]
    backendAddressPools: [
      {
        name: 'defaultBackendPool'
        properties: {
          backendAddresses: []
        }
      }
    ]
    backendHttpSettingsCollection: [
      {
        name: 'defaultHTTPSetting'
        properties: {
          port: 80
          protocol: 'Http'
          cookieBasedAffinity: 'Disabled'
          pickHostNameFromBackendAddress: false
          requestTimeout: 20
        }
      }
    ]
    httpListeners: [
      {
        name: 'http'
        properties: {
          frontendIPConfiguration: {
            id: '/subscriptions/${subscriptionId}/resourceGroups/${rg_network}/providers/Microsoft.Network/applicationGateways/${applicationGatewayName}/frontendIPConfigurations/appGwPublicFrontendIp'
          }
          frontendPort: {
            id: '/subscriptions/${subscriptionId}/resourceGroups/${rg_network}/providers/Microsoft.Network/applicationGateways/${applicationGatewayName}/frontendPorts/port_80'
          }
          protocol: 'Http'
          requireServerNameIndication: false
          hostNames: []
        }
      }
    ]
    requestRoutingRules: [
      {
        name: 'myRoutingRule'
        properties: {
          ruleType: 'Basic'
          priority: 100
          httpListener: {
            id: '/subscriptions/${subscriptionId}/resourceGroups/${rg_network}/providers/Microsoft.Network/applicationGateways/${applicationGatewayName}/httpListeners/http'
          }
          backendAddressPool: {
            id: '/subscriptions/${subscriptionId}/resourceGroups/${rg_network}/providers/Microsoft.Network/applicationGateways/${applicationGatewayName}/backendAddressPools/defaultBackendPool'
          }
          backendHttpSettings: {
            id: '/subscriptions/${subscriptionId}/resourceGroups/${rg_network}/providers/Microsoft.Network/applicationGateways/${applicationGatewayName}/backendHttpSettingsCollection/defaultHTTPSetting'
          }
        }
      }
    ]
    enableHttp2: false
    urlPathMaps: []
    autoscaleMaxCapacity: 10
    autoscaleMinCapacity: 1
  }
  dependsOn: [
    hubResourceGroups
    hubVnet
    createPublicIPAddressForAppGateway
  ]
}

Hope that helps

**Comment by aavdberg** [comment]
Thanks @gsuttie I have it also working without AVM but with AVM I getting the same error as you and it's totally not helpful to troubleshoot.

Why is this issue closed when it's not solved or fixed.

@AlexanderSehr @alex-frankel @jtracey93

**Comment by jtracey93** [comment]
It was closed as no response from the author back in September 👍 

Please open a new issue for this module with the issues you are facing so it can be investigated 👍

**Comment by aavdberg** [comment]
Found the solution to fix this problem.

https://github.com/Azure/bicep-registry-modules/issues/4272

@jtracey93  @alex-frankel @AlexanderSehr @gsuttie
